version: "3.9"

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    container_name: projeto-m3-backend
    restart: always
  db:
    image: mysql:latest
    container_name: projeto-m3-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gerenciamento_projeto
    volumes:
      - /home/dams/mysql:/var/lib/mysql
    restart: always